version: '3.8'

services:
  bulkyweb:
    build:
      context: .
      dockerfile: BulkyWeb2/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      - ollama
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=BulkyDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  sqlserver_data:
  ollama_data: 